use std::sync::{Mutex, OnceLock};

use padauk::padauk_render_root;
use padauk::ui::event_registry::{padauk_dispatch_action, padauk_dispatch_action_with_string};

fn last_render_json() -> &'static Mutex<Option<Vec<u8>>> {
    static LAST_JSON: OnceLock<Mutex<Option<Vec<u8>>>> = OnceLock::new();
    LAST_JSON.get_or_init(|| Mutex::new(None))
}

#[no_mangle]
pub extern "C" fn padauk_web_ready() -> i32 {
    1
}

#[no_mangle]
pub extern "C" fn padauk_web_init() {
    // Initialize the app (generated by #[padauk::main] in the app crate)
    app::padauk_init();
}

#[no_mangle]
pub extern "C" fn padauk_web_render_root_ptr() -> *const u8 {
    let root = padauk_render_root();
    let json = serde_json::to_vec(&root).unwrap_or_else(|_| b"null".to_vec());
    let ptr = json.as_ptr();
    *last_render_json().lock().unwrap() = Some(json);
    ptr
}

#[no_mangle]
pub extern "C" fn padauk_web_render_root_len() -> usize {
    last_render_json()
        .lock()
        .unwrap()
        .as_ref()
        .map(|data| data.len())
        .unwrap_or(0)
}

#[no_mangle]
pub extern "C" fn padauk_web_render_root_free() {
    *last_render_json().lock().unwrap() = None;
}

#[no_mangle]
pub extern "C" fn padauk_web_alloc(len: usize) -> *mut u8 {
    let mut buffer = Vec::<u8>::with_capacity(len);
    let ptr = buffer.as_mut_ptr();
    std::mem::forget(buffer);
    ptr
}

#[no_mangle]
pub extern "C" fn padauk_web_dealloc(ptr: *mut u8, len: usize) {
    if ptr.is_null() || len == 0 {
        return;
    }
    unsafe {
        let _ = Vec::from_raw_parts(ptr, len, len);
    }
}

#[no_mangle]
pub extern "C" fn padauk_web_dispatch_action(ptr: *const u8, len: usize) {
    if ptr.is_null() || len == 0 {
        return;
    }
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    let id = String::from_utf8_lossy(bytes).to_string();
    padauk_dispatch_action(id);
}

#[no_mangle]
pub extern "C" fn padauk_web_dispatch_action_with_string(
    id_ptr: *const u8,
    id_len: usize,
    payload_ptr: *const u8,
    payload_len: usize,
) {
    if id_ptr.is_null() || id_len == 0 {
        return;
    }
    let id_bytes = unsafe { std::slice::from_raw_parts(id_ptr, id_len) };
    let id = String::from_utf8_lossy(id_bytes).to_string();

    let payload = if payload_ptr.is_null() || payload_len == 0 {
        String::new()
    } else {
        let payload_bytes = unsafe { std::slice::from_raw_parts(payload_ptr, payload_len) };
        String::from_utf8_lossy(payload_bytes).to_string()
    };

    padauk_dispatch_action_with_string(id, payload);
}
