// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package rs.padauk.core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_padauk_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_padauk_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "padauk"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfaceRenderCallbackMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceResourceLoaderMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`name`: RustBuffer.ByValue,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("uniffiFree", "uniffiClone", "onUpdate")
internal open class UniffiVTableCallbackInterfaceRenderCallback(
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    @JvmField internal var `uniffiClone`: UniffiCallbackInterfaceClone? = null,
    @JvmField internal var `onUpdate`: UniffiCallbackInterfaceRenderCallbackMethod0? = null,
) : Structure() {
    class UniffiByValue(
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
        `uniffiClone`: UniffiCallbackInterfaceClone? = null,
        `onUpdate`: UniffiCallbackInterfaceRenderCallbackMethod0? = null,
    ): UniffiVTableCallbackInterfaceRenderCallback(`uniffiFree`,`uniffiClone`,`onUpdate`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceRenderCallback) {
        `uniffiFree` = other.`uniffiFree`
        `uniffiClone` = other.`uniffiClone`
        `onUpdate` = other.`onUpdate`
    }

}
@Structure.FieldOrder("uniffiFree", "uniffiClone", "loadRawResource")
internal open class UniffiVTableCallbackInterfaceResourceLoader(
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    @JvmField internal var `uniffiClone`: UniffiCallbackInterfaceClone? = null,
    @JvmField internal var `loadRawResource`: UniffiCallbackInterfaceResourceLoaderMethod0? = null,
) : Structure() {
    class UniffiByValue(
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
        `uniffiClone`: UniffiCallbackInterfaceClone? = null,
        `loadRawResource`: UniffiCallbackInterfaceResourceLoaderMethod0? = null,
    ): UniffiVTableCallbackInterfaceResourceLoader(`uniffiFree`,`uniffiClone`,`loadRawResource`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceResourceLoader) {
        `uniffiFree` = other.`uniffiFree`
        `uniffiClone` = other.`uniffiClone`
        `loadRawResource` = other.`loadRawResource`
    }

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "padauk"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_padauk_checksum_func_init_logging(
    ): Short
    external fun uniffi_padauk_checksum_func_padauk_dispatch_action(
    ): Short
    external fun uniffi_padauk_checksum_func_padauk_nav_can_pop(
    ): Short
    external fun uniffi_padauk_checksum_func_padauk_nav_pop(
    ): Short
    external fun uniffi_padauk_checksum_func_padauk_render_root(
    ): Short
    external fun uniffi_padauk_checksum_func_register_render_callback(
    ): Short
    external fun uniffi_padauk_checksum_func_register_resource_loader(
    ): Short
    external fun uniffi_padauk_checksum_method_rendercallback_on_update(
    ): Short
    external fun uniffi_padauk_checksum_method_resourceloader_load_raw_resource(
    ): Short
    external fun ffi_padauk_uniffi_contract_version(
    ): Int
    
        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "padauk"))
        uniffiCallbackInterfaceRenderCallback.register(this)
        uniffiCallbackInterfaceResourceLoader.register(this)
        
    }
    external fun uniffi_padauk_fn_init_callback_vtable_rendercallback(`vtable`: UniffiVTableCallbackInterfaceRenderCallback,
    ): Unit
    external fun uniffi_padauk_fn_init_callback_vtable_resourceloader(`vtable`: UniffiVTableCallbackInterfaceResourceLoader,
    ): Unit
    external fun uniffi_padauk_fn_func_init_logging(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_padauk_fn_func_padauk_dispatch_action(`id`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_padauk_fn_func_padauk_nav_can_pop(uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_padauk_fn_func_padauk_nav_pop(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_padauk_fn_func_padauk_render_root(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_padauk_fn_func_register_render_callback(`callback`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_padauk_fn_func_register_resource_loader(`loader`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_padauk_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_padauk_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_padauk_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_padauk_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_padauk_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_padauk_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_padauk_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_padauk_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_padauk_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_padauk_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_padauk_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_padauk_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_padauk_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_padauk_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_padauk_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_padauk_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_padauk_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    
        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_padauk_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_padauk_checksum_func_init_logging() != 51795.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_func_padauk_dispatch_action() != 6256.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_func_padauk_nav_can_pop() != 9472.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_func_padauk_nav_pop() != 12885.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_func_padauk_render_root() != 49349.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_func_register_render_callback() != 17765.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_func_register_resource_loader() != 36297.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_method_rendercallback_on_update() != 50468.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_padauk_checksum_method_resourceloader_load_raw_resource() != 54703.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class Modifiers (
    var `padding`: kotlin.Float
    , 
    var `backgroundColor`: kotlin.String?
    , 
    var `width`: kotlin.Float?
    , 
    var `height`: kotlin.Float?
    
){
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeModifiers: FfiConverterRustBuffer<Modifiers> {
    override fun read(buf: ByteBuffer): Modifiers {
        return Modifiers(
            FfiConverterFloat.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalFloat.read(buf),
            FfiConverterOptionalFloat.read(buf),
        )
    }

    override fun allocationSize(value: Modifiers) = (
            FfiConverterFloat.allocationSize(value.`padding`) +
            FfiConverterOptionalString.allocationSize(value.`backgroundColor`) +
            FfiConverterOptionalFloat.allocationSize(value.`width`) +
            FfiConverterOptionalFloat.allocationSize(value.`height`)
    )

    override fun write(value: Modifiers, buf: ByteBuffer) {
            FfiConverterFloat.write(value.`padding`, buf)
            FfiConverterOptionalString.write(value.`backgroundColor`, buf)
            FfiConverterOptionalFloat.write(value.`width`, buf)
            FfiConverterOptionalFloat.write(value.`height`, buf)
    }
}



sealed class AndroidUiNode {
    
    data class Column(
        val `children`: List<AndroidUiNode>, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    
    data class Row(
        val `children`: List<AndroidUiNode>, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    
    data class Stack(
        val `children`: List<AndroidUiNode>, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    
    data class Scaffold(
        val `appBar`: List<AndroidUiNode>, 
        val `body`: List<AndroidUiNode>, 
        val `floatingActionButton`: List<AndroidUiNode>, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    
    data class AppBar(
        val `title`: kotlin.String, 
        val `leading`: List<AndroidUiNode>, 
        val `style`: AppBarStyle, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    
    data class Text(
        val `text`: kotlin.String, 
        val `spSize`: kotlin.Float, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    
    data class Button(
        val `actionId`: kotlin.String, 
        val `content`: List<AndroidUiNode>, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    
    data class Image(
        val `source`: ImageSource, 
        val `fit`: BoxFit, 
        val `modifiers`: Modifiers) : AndroidUiNode()
        
    {
        

        companion object
    }
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAndroidUiNode : FfiConverterRustBuffer<AndroidUiNode>{
    override fun read(buf: ByteBuffer): AndroidUiNode {
        return when(buf.getInt()) {
            1 -> AndroidUiNode.Column(
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            2 -> AndroidUiNode.Row(
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            3 -> AndroidUiNode.Stack(
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            4 -> AndroidUiNode.Scaffold(
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            5 -> AndroidUiNode.AppBar(
                FfiConverterString.read(buf),
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterTypeAppBarStyle.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            6 -> AndroidUiNode.Text(
                FfiConverterString.read(buf),
                FfiConverterFloat.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            7 -> AndroidUiNode.Button(
                FfiConverterString.read(buf),
                FfiConverterSequenceTypeAndroidUiNode.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            8 -> AndroidUiNode.Image(
                FfiConverterTypeImageSource.read(buf),
                FfiConverterTypeBoxFit.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: AndroidUiNode) = when(value) {
        is AndroidUiNode.Column -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`children`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
        is AndroidUiNode.Row -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`children`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
        is AndroidUiNode.Stack -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`children`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
        is AndroidUiNode.Scaffold -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`appBar`)
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`body`)
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`floatingActionButton`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
        is AndroidUiNode.AppBar -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`title`)
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`leading`)
                + FfiConverterTypeAppBarStyle.allocationSize(value.`style`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
        is AndroidUiNode.Text -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`text`)
                + FfiConverterFloat.allocationSize(value.`spSize`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
        is AndroidUiNode.Button -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`actionId`)
                + FfiConverterSequenceTypeAndroidUiNode.allocationSize(value.`content`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
        is AndroidUiNode.Image -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeImageSource.allocationSize(value.`source`)
                + FfiConverterTypeBoxFit.allocationSize(value.`fit`)
                + FfiConverterTypeModifiers.allocationSize(value.`modifiers`)
            )
        }
    }

    override fun write(value: AndroidUiNode, buf: ByteBuffer) {
        when(value) {
            is AndroidUiNode.Column -> {
                buf.putInt(1)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`children`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
            is AndroidUiNode.Row -> {
                buf.putInt(2)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`children`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
            is AndroidUiNode.Stack -> {
                buf.putInt(3)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`children`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
            is AndroidUiNode.Scaffold -> {
                buf.putInt(4)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`appBar`, buf)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`body`, buf)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`floatingActionButton`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
            is AndroidUiNode.AppBar -> {
                buf.putInt(5)
                FfiConverterString.write(value.`title`, buf)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`leading`, buf)
                FfiConverterTypeAppBarStyle.write(value.`style`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
            is AndroidUiNode.Text -> {
                buf.putInt(6)
                FfiConverterString.write(value.`text`, buf)
                FfiConverterFloat.write(value.`spSize`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
            is AndroidUiNode.Button -> {
                buf.putInt(7)
                FfiConverterString.write(value.`actionId`, buf)
                FfiConverterSequenceTypeAndroidUiNode.write(value.`content`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
            is AndroidUiNode.Image -> {
                buf.putInt(8)
                FfiConverterTypeImageSource.write(value.`source`, buf)
                FfiConverterTypeBoxFit.write(value.`fit`, buf)
                FfiConverterTypeModifiers.write(value.`modifiers`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class AppBarStyle {
    
    SMALL,
    CENTER_ALIGNED,
    MEDIUM,
    LARGE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeAppBarStyle: FfiConverterRustBuffer<AppBarStyle> {
    override fun read(buf: ByteBuffer) = try {
        AppBarStyle.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AppBarStyle) = 4UL

    override fun write(value: AppBarStyle, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class BoxFit {
    
    CONTAIN,
    COVER,
    FILL,
    FIT_WIDTH,
    FIT_HEIGHT,
    NONE,
    SCALE_DOWN;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeBoxFit: FfiConverterRustBuffer<BoxFit> {
    override fun read(buf: ByteBuffer) = try {
        BoxFit.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: BoxFit) = 4UL

    override fun write(value: BoxFit, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





sealed class ImageSource {
    
    data class Asset(
        val `name`: kotlin.String) : ImageSource()
        
    {
        

        companion object
    }
    
    data class Network(
        val `url`: kotlin.String) : ImageSource()
        
    {
        

        companion object
    }
    
    data class File(
        val `path`: kotlin.String) : ImageSource()
        
    {
        

        companion object
    }
    
    data class Memory(
        val `data`: kotlin.ByteArray) : ImageSource()
        
    {
        

        companion object
    }
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeImageSource : FfiConverterRustBuffer<ImageSource>{
    override fun read(buf: ByteBuffer): ImageSource {
        return when(buf.getInt()) {
            1 -> ImageSource.Asset(
                FfiConverterString.read(buf),
                )
            2 -> ImageSource.Network(
                FfiConverterString.read(buf),
                )
            3 -> ImageSource.File(
                FfiConverterString.read(buf),
                )
            4 -> ImageSource.Memory(
                FfiConverterByteArray.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ImageSource) = when(value) {
        is ImageSource.Asset -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`name`)
            )
        }
        is ImageSource.Network -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`url`)
            )
        }
        is ImageSource.File -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`path`)
            )
        }
        is ImageSource.Memory -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterByteArray.allocationSize(value.`data`)
            )
        }
    }

    override fun write(value: ImageSource, buf: ByteBuffer) {
        when(value) {
            is ImageSource.Asset -> {
                buf.putInt(1)
                FfiConverterString.write(value.`name`, buf)
                Unit
            }
            is ImageSource.Network -> {
                buf.putInt(2)
                FfiConverterString.write(value.`url`, buf)
                Unit
            }
            is ImageSource.File -> {
                buf.putInt(3)
                FfiConverterString.write(value.`path`, buf)
                Unit
            }
            is ImageSource.Memory -> {
                buf.putInt(4)
                FfiConverterByteArray.write(value.`data`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}





sealed class IosUiNode {
    
    data class VStack(
        val `views`: List<IosUiNode>, 
        val `attributes`: Modifiers) : IosUiNode()
        
    {
        

        companion object
    }
    
    data class Label(
        val `title`: kotlin.String, 
        val `ptSize`: kotlin.Float, 
        val `attributes`: Modifiers) : IosUiNode()
        
    {
        

        companion object
    }
    
    data class Button(
        val `actionId`: kotlin.String, 
        val `label`: List<IosUiNode>, 
        val `attributes`: Modifiers) : IosUiNode()
        
    {
        

        companion object
    }
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIosUiNode : FfiConverterRustBuffer<IosUiNode>{
    override fun read(buf: ByteBuffer): IosUiNode {
        return when(buf.getInt()) {
            1 -> IosUiNode.VStack(
                FfiConverterSequenceTypeIosUiNode.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            2 -> IosUiNode.Label(
                FfiConverterString.read(buf),
                FfiConverterFloat.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            3 -> IosUiNode.Button(
                FfiConverterString.read(buf),
                FfiConverterSequenceTypeIosUiNode.read(buf),
                FfiConverterTypeModifiers.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: IosUiNode) = when(value) {
        is IosUiNode.VStack -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterSequenceTypeIosUiNode.allocationSize(value.`views`)
                + FfiConverterTypeModifiers.allocationSize(value.`attributes`)
            )
        }
        is IosUiNode.Label -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`title`)
                + FfiConverterFloat.allocationSize(value.`ptSize`)
                + FfiConverterTypeModifiers.allocationSize(value.`attributes`)
            )
        }
        is IosUiNode.Button -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`actionId`)
                + FfiConverterSequenceTypeIosUiNode.allocationSize(value.`label`)
                + FfiConverterTypeModifiers.allocationSize(value.`attributes`)
            )
        }
    }

    override fun write(value: IosUiNode, buf: ByteBuffer) {
        when(value) {
            is IosUiNode.VStack -> {
                buf.putInt(1)
                FfiConverterSequenceTypeIosUiNode.write(value.`views`, buf)
                FfiConverterTypeModifiers.write(value.`attributes`, buf)
                Unit
            }
            is IosUiNode.Label -> {
                buf.putInt(2)
                FfiConverterString.write(value.`title`, buf)
                FfiConverterFloat.write(value.`ptSize`, buf)
                FfiConverterTypeModifiers.write(value.`attributes`, buf)
                Unit
            }
            is IosUiNode.Button -> {
                buf.putInt(3)
                FfiConverterString.write(value.`actionId`, buf)
                FfiConverterSequenceTypeIosUiNode.write(value.`label`, buf)
                FfiConverterTypeModifiers.write(value.`attributes`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class MainAxisAlignment {
    
    START,
    CENTER,
    END,
    SPACE_BETWEEN;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMainAxisAlignment: FfiConverterRustBuffer<MainAxisAlignment> {
    override fun read(buf: ByteBuffer) = try {
        MainAxisAlignment.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: MainAxisAlignment) = 4UL

    override fun write(value: MainAxisAlignment, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class PlatformException: kotlin.Exception() {
    
    class NotFound(
        
        val `name`: kotlin.String
        ) : PlatformException() {
        override val message
            get() = "name=${ `name` }"
    }
    
    class Generic(
        
        val `details`: kotlin.String
        ) : PlatformException() {
        override val message
            get() = "details=${ `details` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<PlatformException> {
        override fun lift(error_buf: RustBuffer.ByValue): PlatformException = FfiConverterTypePlatformError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypePlatformError : FfiConverterRustBuffer<PlatformException> {
    override fun read(buf: ByteBuffer): PlatformException {
        

        return when(buf.getInt()) {
            1 -> PlatformException.NotFound(
                FfiConverterString.read(buf),
                )
            2 -> PlatformException.Generic(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: PlatformException): ULong {
        return when(value) {
            is PlatformException.NotFound -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`name`)
            )
            is PlatformException.Generic -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`details`)
            )
        }
    }

    override fun write(value: PlatformException, buf: ByteBuffer) {
        when(value) {
            is PlatformException.NotFound -> {
                buf.putInt(1)
                FfiConverterString.write(value.`name`, buf)
                Unit
            }
            is PlatformException.Generic -> {
                buf.putInt(2)
                FfiConverterString.write(value.`details`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





public interface RenderCallback {
    
    fun `onUpdate`()
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceRenderCallback {
    internal object `onUpdate`: UniffiCallbackInterfaceRenderCallbackMethod0 {
        override fun callback(`uniffiHandle`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeRenderCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onUpdate`(
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeRenderCallback.handleMap.remove(handle)
        }
    }

    internal object uniffiClone: UniffiCallbackInterfaceClone {
        override fun callback(handle: Long): Long {
            return FfiConverterTypeRenderCallback.handleMap.clone(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceRenderCallback.UniffiByValue(
        uniffiFree,
        uniffiClone,
        `onUpdate`,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_padauk_fn_init_callback_vtable_rendercallback(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeRenderCallback: FfiConverterCallbackInterface<RenderCallback>()





public interface ResourceLoader {
    
    /**
     * Returns the bytes of the file, or a PlatformError
     */
    fun `loadRawResource`(`name`: kotlin.String): kotlin.ByteArray
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceResourceLoader {
    internal object `loadRawResource`: UniffiCallbackInterfaceResourceLoaderMethod0 {
        override fun callback(`uniffiHandle`: Long,`name`: RustBuffer.ByValue,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeResourceLoader.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`loadRawResource`(
                    FfiConverterString.lift(`name`),
                )
            }
            val writeReturn = { value: kotlin.ByteArray -> uniffiOutReturn.setValue(FfiConverterByteArray.lower(value)) }
            uniffiTraitInterfaceCallWithError(
                uniffiCallStatus,
                makeCall,
                writeReturn,
                { e: PlatformException -> FfiConverterTypePlatformError.lower(e) }
            )
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeResourceLoader.handleMap.remove(handle)
        }
    }

    internal object uniffiClone: UniffiCallbackInterfaceClone {
        override fun callback(handle: Long): Long {
            return FfiConverterTypeResourceLoader.handleMap.clone(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceResourceLoader.UniffiByValue(
        uniffiFree,
        uniffiClone,
        `loadRawResource`,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_padauk_fn_init_callback_vtable_resourceloader(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeResourceLoader: FfiConverterCallbackInterface<ResourceLoader>()




/**
 * @suppress
 */
public object FfiConverterOptionalFloat: FfiConverterRustBuffer<kotlin.Float?> {
    override fun read(buf: ByteBuffer): kotlin.Float? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterFloat.read(buf)
    }

    override fun allocationSize(value: kotlin.Float?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterFloat.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Float?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterFloat.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeAndroidUiNode: FfiConverterRustBuffer<List<AndroidUiNode>> {
    override fun read(buf: ByteBuffer): List<AndroidUiNode> {
        val len = buf.getInt()
        return List<AndroidUiNode>(len) {
            FfiConverterTypeAndroidUiNode.read(buf)
        }
    }

    override fun allocationSize(value: List<AndroidUiNode>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeAndroidUiNode.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<AndroidUiNode>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeAndroidUiNode.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeIosUiNode: FfiConverterRustBuffer<List<IosUiNode>> {
    override fun read(buf: ByteBuffer): List<IosUiNode> {
        val len = buf.getInt()
        return List<IosUiNode>(len) {
            FfiConverterTypeIosUiNode.read(buf)
        }
    }

    override fun allocationSize(value: List<IosUiNode>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeIosUiNode.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<IosUiNode>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeIosUiNode.write(it, buf)
        }
    }
} fun `initLogging`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_padauk_fn_func_init_logging(
    
        _status)
}
    
    
 fun `padaukDispatchAction`(`id`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_padauk_fn_func_padauk_dispatch_action(
    
        FfiConverterString.lower(`id`),_status)
}
    
    
 fun `padaukNavCanPop`(): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_padauk_fn_func_padauk_nav_can_pop(
    
        _status)
}
    )
    }
    
 fun `padaukNavPop`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_padauk_fn_func_padauk_nav_pop(
    
        _status)
}
    
    
 fun `padaukRenderRoot`(): AndroidUiNode {
            return FfiConverterTypeAndroidUiNode.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_padauk_fn_func_padauk_render_root(
    
        _status)
}
    )
    }
    
 fun `registerRenderCallback`(`callback`: RenderCallback)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_padauk_fn_func_register_render_callback(
    
        FfiConverterTypeRenderCallback.lower(`callback`),_status)
}
    
    
 fun `registerResourceLoader`(`loader`: ResourceLoader)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_padauk_fn_func_register_resource_loader(
    
        FfiConverterTypeResourceLoader.lower(`loader`),_status)
}
    
    


