#[derive(uniffi::Record, Default, Clone)]
pub struct Modifiers {
    pub padding: Option<f32>,
    pub padding_horizontal: Option<f32>,
    pub padding_vertical: Option<f32>,
    pub background_color: Option<crate::ui::color::ColorValue>,
    pub width: Option<f32>,
    pub height: Option<f32>,
    pub fill_max_width: bool,
    pub fill_max_height: bool,
    pub weight: Option<f32>,
    pub weight_fill: Option<bool>,
    pub border_width: Option<f32>,
    pub border_color: Option<crate::ui::color::ColorValue>,
    pub alpha: Option<f32>,
    pub clip: bool,
    pub corner_radius: Option<f32>,
    pub offset_x: Option<f32>,
    pub offset_y: Option<f32>,
    pub z_index: Option<f32>,
    pub enabled: Option<bool>,
}
